export const products = [
    {
      name: 'iPhone 11',
      description: "A light green apple iPhone 11",
        image: '/images/1.jpg',
        price: 400,
      id: 0,
      data: 'ids',
    },
    {
      name: 'iPhone 7 +',
      description:"An apple iPhone 7 plus",
      image: '/images/2.jpg',
      price: 120,
      id: 1,
      data: 'ids',
    },
    {
      name: 'iPhone 8',
      description:"An apple iPhone 8",
      image: '/images/3.jpg',
      price: 100,
      id: 2,
      data: 'ids',
    },
    {
        name: 'Samsung Note 21',
        description:"A black Samsung galaxy note 21",
        image: '/images/4.jpg',
        price: 850,
        id: 3,
        data: 'ids',
      },
      {
        name: 'Samsung S9 plus',
        description:"A black Samsung galaxy S9 Plus",
        image: '/images/5.jpg',
        price: 650,
        id: 4,
        data: 'ids',
      },
      {
        name: 'Iphone 11 pro max',
        description:"A white Iphone 11 pro max",
        image: '/images/6.jpg',
        price: 800,
        id: 5,
        data: 'ids',
      },
      {
        name: 'Apple Watch',
        description:"An apple watch different colors available",
        image: '/images/7.jpg',
        price: 90,
        id: 6,
        data: 'ids',
      },
      {
        name: 'Apple Watch',
        description:"An apple watch different colors available",
        image: '/images/8.jpg',
        price: 100,
        id: 7,
        data: 'ids',
      },
      {
        name: 'Apple airpods casing',
        description:"A white apple airpods casing",
        image: '/images/9.jpg',
        price: 100,
        id: 8,
        data: 'ids',
      },
      {
        name: 'iWatch',
        description:"An apple watch.",
        image: '/images/10.jpg',
        price: 100,
        id: 9,
        data: 'ids',
      },
      {
        name: 'Iphone 12 pro max',
        description:"An iPhone 12 pro max.",
        image: '/images/11.jpg',
        price: 900,
        id: 10,
        data: 'ids',
      },
      {
        name: 'iPhone X',
        description:"An apple iPhone X.",
        image: '/images/12.jpg',
        price: 600,
        id: 11,
        data: 'ids',
      },
  ];

export const logos = [
  {
    image: '/images/commerce.png',
    id: 0,
  }
]